// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingApp.Backend.DataAccess;

#nullable disable

namespace VotingApp.Backend.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230917093642_ForeignKey_Voter_Vote")]
    partial class ForeignKey_Voter_Vote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VotingApp.Backend.DataAccess.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("VotingApp.Backend.DataAccess.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("VotingApp.Backend.DataAccess.Entities.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoteId")
                        .IsUnique()
                        .HasFilter("[VoteId] IS NOT NULL");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("VotingApp.Backend.DataAccess.Entities.Vote", b =>
                {
                    b.HasOne("VotingApp.Backend.DataAccess.Entities.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("VotingApp.Backend.DataAccess.Entities.Voter", b =>
                {
                    b.HasOne("VotingApp.Backend.DataAccess.Entities.Vote", "Vote")
                        .WithOne("Voter")
                        .HasForeignKey("VotingApp.Backend.DataAccess.Entities.Voter", "VoteId");

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("VotingApp.Backend.DataAccess.Entities.Candidate", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("VotingApp.Backend.DataAccess.Entities.Vote", b =>
                {
                    b.Navigation("Voter")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
